show databases;
use customer_behaviour;
s\	how tables;

select *from customers;

-- 1. What is total revenue generated by male vs female customers.
select gender,sum(purchase_amount) as total_revenue from customers group by gender;

-- 2. Which customer used a discount but still spent more than the average purchase amount.
SELECT customer_id,
  purchase_amount
FROM customers
WHERE discount_applied = 'Yes'
  AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customers
  );


-- 3. Which are the top 5 products with the highest average review rating.
SELECT item_purchased,
ROUND(AVG(review_rating), 2) AS "Average Product Rating"
FROM customers
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- 4. compare the average purchase amount between standard and express shipping.
SELECT shipping_type,
  ROUND(AVG(purchase_amount), 2)
FROM customers
WHERE shipping_type IN (
  'Standard', 'Express'
)



-- 5. Do subscribed customers spend more? compare average spend and total revenue between subscibers and non subscibers
SELECT subscription_status,
COUNT(customer_id)           AS total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customers
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;



-- 6. which five products have the highest percentage of purchases with discount applied
SELECT item_purchased,
  ROUND(
    SUM(CASE
      WHEN discount_applied = 'Yes'
      THEN 1 ELSE 0
    END) / COUNT(*) * 100, 2
  ) AS discount_rate
FROM customers
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. segement customers into new,returning and loyal based on their total number of previous purchases and show the count of each segment.
WITH customer_type AS (
  SELECT customer_id,
    previous_purchases,
    CASE
      WHEN previous_purchases = 1
        THEN 'New'
      WHEN previous_purchases
        BETWEEN 2 AND 10
        THEN 'Returning'
      ELSE 'Loyal'
    END AS customer_segment
  FROM customers
)
SELECT customer_segment,
  COUNT(*) AS Number_of_Customers
FROM customer_type
GROUP BY customer_segment;



-- 8. what are the top 3 most purchased products within each 
with item_counts as (
select category, 
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) DESC) as item_rank
from customers
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;




-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customers
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. What is the revenue contribution of each age group?

SELECT 
CASE
    WHEN age < 20 THEN 'Teen'
    WHEN age BETWEEN 20 AND 35 THEN 'Young Adult'
    WHEN age BETWEEN 36 AND 50 THEN 'Adult'
    ELSE 'Senior'
END AS age_group,

SUM(purchase_amount) AS total_revenue

FROM customers
GROUP BY age_group
ORDER BY total_revenue DESC;


